version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: flask_db
    depends_on:
      - db
    networks:
      - flask-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - flask-net

networks:
  flask-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
