

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
    networks:
      - flask-net
    volumes:
      - sqldata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"

  flask-app:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=db
    networks:
      - flask-net
    ports:
      - "5000:5000"
    depends_on:
      - db

networks:
  flask-net:
    driver: bridge

volumes:
  sqldata:
