name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Build and Test Docker Images
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Image
        run: |
          docker-compose build

      - name: Test Application
        run: |
          docker-compose up -d
          sleep 10
          curl -f http://localhost:5000 && echo "Test Passed!" || (echo "Test Failed!" && exit 1)
          docker-compose down

  # Step 2: Setup Google Cloud SDK and Authenticate
  setup-gcloud:
    runs-on: ubuntu-22.04
    needs: build_and_test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Verify gcloud Installation
        run: gcloud --version

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Project and Region
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region ${{ secrets.GKE_CLUSTER_REGION }}

  # Step 3: Deploy to GKE Cluster with Terraform
  deploy:
    runs-on: ubuntu-22.04
    needs: setup-gcloud
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Plan
        run: |
          terraform plan
          terraform apply -auto-approve

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_CLUSTER_REGION }}

      - name: Deploy to GKE with kubectl
        run: |
          kubectl apply -f k8s/  # Replace this with your actual Kubernetes YAML files


      

      
